"""
Tools used by the Google ADK Search Planner Agent.

v0.9 removes application-level assumptions about Houston, Pediatric Dentistry,
and provider discovery. The model interprets the user's request; this tool
validates the structured values and delegates deterministic SearchPlan
construction to QueryFanoutPlanner.
"""

from models import SearchIntent, UserQuery
from search.query_fanout import QueryFanoutPlanner


def _normalize_optional(value: str | None) -> str | None:
    if value is None:
        return None

    normalized = value.strip()
    return normalized or None


def create_healthcare_search_plan(
    question: str,
    intent: str,
    generated_queries: list[str],
    location: str | None = None,
    specialty: str | None = None,
) -> dict:
    """
    Validate semantic planning output and create a structured healthcare search plan.

    Args:
        question: The user's healthcare question.
        intent: One SearchIntent value, such as provider_discovery or
            biomedical_research.
        generated_queries: Concise retrieval-oriented queries generated by the
            Search Planner Agent.
        location: Optional geographic location when relevant to the request.
        specialty: Optional healthcare specialty/provider type/care domain.

    Returns:
        Structured UserQuery and SearchPlan dictionaries suitable for ADK state.
    """

    validated_intent = SearchIntent(intent)

    user_query = UserQuery(
        text=question.strip(),
        location=_normalize_optional(location),
        specialty=_normalize_optional(specialty),
        intent=validated_intent,
    )

    planner = QueryFanoutPlanner()
    plan = planner.create_plan(
        user_query=user_query,
        generated_queries=generated_queries,
    )

    return {
        "user_query": user_query.model_dump(mode="json"),
        "search_plan": plan.model_dump(mode="json"),
    }
