"""
Deterministic query-fan-out plan construction.

The Search Planner Agent owns semantic interpretation and query generation.
This module owns validation, normalization, deduplication, and construction of
the domain SearchPlan model.

v0.9 intentionally contains no direct LLM/Gemini dependency. This keeps the
planning domain layer usable with either Gemini or Gemma through Google ADK.
"""

from collections.abc import Iterable

from models import SearchIntent, SearchPlan, SearchQuery, UserQuery


class QueryFanoutPlanner:
    """Build validated SearchPlan objects from already-interpreted planner state."""

    MAX_GENERATED_QUERIES = 8

    def create_plan(
        self,
        user_query: UserQuery,
        generated_queries: Iterable[str] | None = None,
    ) -> SearchPlan:
        """Create a deterministic SearchPlan without making an LLM call."""

        if user_query.intent is None:
            raise ValueError("UserQuery.intent is required to create a SearchPlan.")

        normalized_queries = self._normalize_queries(generated_queries or [])

        if not normalized_queries:
            normalized_queries = self._fallback_queries(user_query)

        search_queries = [
            SearchQuery(
                query=query,
                purpose=self._purpose_for(user_query.intent, index),
                priority=self._priority_for(index),
            )
            for index, query in enumerate(normalized_queries)
        ]

        return SearchPlan(
            original_query=user_query,
            intent=user_query.intent,
            generated_queries=search_queries,
            notes=(
                "Search queries were semantically generated by the Search Planner Agent "
                "and deterministically validated by QueryFanoutPlanner."
            ),
        )

    def _normalize_queries(self, queries: Iterable[str]) -> list[str]:
        normalized: list[str] = []
        seen: set[str] = set()

        for raw_query in queries:
            if not isinstance(raw_query, str):
                raise ValueError("generated_queries must contain only strings.")

            query = " ".join(raw_query.split())
            if len(query) < 3:
                continue

            key = query.casefold()
            if key in seen:
                continue

            seen.add(key)
            normalized.append(query)

            if len(normalized) >= self.MAX_GENERATED_QUERIES:
                break

        return normalized

    def _fallback_queries(self, user_query: UserQuery) -> list[str]:
        """Provide a safe compatibility fallback when no fan-out was supplied."""

        parts = [user_query.specialty, user_query.location]
        scoped = " ".join(part for part in parts if part)

        if user_query.intent == SearchIntent.PROVIDER_DISCOVERY and scoped:
            return [scoped]

        return [user_query.text]

    @staticmethod
    def _priority_for(index: int) -> int:
        # Preserve a compact 1-5 priority range while keeping earlier queries
        # slightly more important than later fan-out queries.
        return min(index + 1, 5)

    @staticmethod
    def _purpose_for(intent: SearchIntent, index: int) -> str:
        labels = {
            SearchIntent.PROVIDER_DISCOVERY: "Retrieve provider-discovery evidence",
            SearchIntent.CARE_PROGRAM_DISCOVERY: "Retrieve care-program discovery evidence",
            SearchIntent.HEALTH_INFORMATION: "Retrieve healthcare information evidence",
            SearchIntent.BIOMEDICAL_RESEARCH: "Retrieve biomedical research evidence",
            SearchIntent.CLINICAL_TRIALS: "Retrieve clinical-trial discovery evidence",
        }
        return f"{labels[intent]} (fan-out query {index + 1})."
