apiVersion: v1
kind: Service
metadata:
  name: healthcare-ai-service
  namespace: healthcare-ai
spec:
  selector:
    app: healthcare-ai-app
  ports:
    - name: http
      port: 8501
      targetPort: 8501
  type: ClusterIP